"""
StreamVault Server Engine v3.0 - YouTube Downloader API
Fast extract_flat metadata pass + oEmbed fallback
"""
import http.server
import socketserver
import os
import re
import json
import tempfile
import urllib.request
import urllib.parse
import threading
import time
import shutil
import yt_dlp
import imageio_ffmpeg
import uuid

import http.cookiejar
import zipfile
import io

PORT = int(os.environ.get('PORT', 7777))
TOKEN_FILE = 'yt_tokens.json'
active_downloads = {}

def ensure_deno_installed():
    try:
        deno_dir = os.path.join(tempfile.gettempdir(), 'deno_bin')
        os.makedirs(deno_dir, exist_ok=True)
        deno_exe = os.path.join(deno_dir, 'deno.exe' if os.name == 'nt' else 'deno')
        if not os.path.exists(deno_exe):
            print("Downloading Deno JS engine for yt-dlp signature solving...")
            if os.name == 'nt':
                url = "https://github.com/denoland/deno/releases/latest/download/deno-x86_64-pc-windows-msvc.zip"
            else:
                url = "https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip"
            req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
            with urllib.request.urlopen(req, timeout=30) as resp:
                z = zipfile.ZipFile(io.BytesIO(resp.read()))
                z.extractall(deno_dir)
            if os.name != 'nt' and os.path.exists(deno_exe):
                os.chmod(deno_exe, 0o755)
        os.environ['PATH'] = deno_dir + os.pathsep + os.environ.get('PATH', '')
        print(f"Deno JS engine ready at: {deno_exe}")
        return deno_exe
    except Exception as e:
        print(f"Deno install warning: {e}")
        return None

# Ensure Deno JS Engine is ready on server start
DENO_EXE_PATH = ensure_deno_installed()

def ensure_youtube_cookies(cookies_file):
    try:
        with open(cookies_file, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n# This file was generated by StreamVault\n")
    except Exception:
        pass

# Ensure FFmpeg is available on PATH for StreamVault engine
try:
    ffmpeg_exe = imageio_ffmpeg.get_ffmpeg_exe()
    ffmpeg_dir = os.path.dirname(ffmpeg_exe)
    target_ffmpeg = os.path.join(ffmpeg_dir, 'ffmpeg.exe')
    if not os.path.exists(target_ffmpeg):
        import shutil
        shutil.copyfile(ffmpeg_exe, target_ffmpeg)
    os.environ["PATH"] += os.pathsep + ffmpeg_dir
except Exception as e:
    print(f"FFmpeg init warning: {e}")

def format_duration(seconds):
    if not seconds: return "Unknown"
    seconds = int(seconds)
    hours = seconds // 3600
    minutes = (seconds % 3600) // 60
    secs = seconds % 60
    return f"{hours:02d}:{minutes:02d}:{secs:02d}" if hours > 0 else f"{minutes:02d}:{secs:02d}"

def get_real_youtube_metadata(video_id):
    if not video_id: return 0
    url = f"https://www.youtube.com/watch?v={video_id}"
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36'})
    try:
        with urllib.request.urlopen(req, timeout=6) as r:
            html = r.read().decode('utf-8', errors='ignore')
            view_m = re.search(r'"viewCount":"(\d+)"', html) or re.search(r'"viewCount":\s*"(\d+)"', html) or re.search(r'(\d[\d,]+)\s+views', html)
            if view_m:
                val = view_m.group(1).replace(',', '')
                if val.isdigit():
                    return int(val)
    except Exception:
        pass
    return 0

def format_size(bytes_num):
    if not bytes_num: return "N/A"
    bytes_num = int(bytes_num)
    if bytes_num >= 1024 * 1024 * 1024: return f"{bytes_num / (1024**3):.1f} GB"
    if bytes_num >= 1024 * 1024: return f"{bytes_num / (1024**2):.1f} MB"
    if bytes_num >= 1024: return f"{bytes_num / 1024:.1f} KB"
    return f"{bytes_num} B"

def parse_time_to_seconds(time_val):
    if not time_val: return None
    parts = str(time_val).strip().split(':')
    try:
        if len(parts) == 3: return float(parts[0]) * 3600 + float(parts[1]) * 60 + float(parts[2])
        if len(parts) == 2: return float(parts[0]) * 60 + float(parts[1])
        return float(parts[0])
    except ValueError:
        return None

SERVER_DIR = os.path.dirname(os.path.abspath(__file__))

class SPAServer(http.server.SimpleHTTPRequestHandler):
    def translate_path(self, path):
        clean = path.split('?')[0].rstrip('/')
        if clean in ['/sitemap.xml', '/sitemap']:
            for candidate in [os.path.join(SERVER_DIR, 'sitemap.xml'), os.path.join(os.path.dirname(SERVER_DIR), 'sitemap.xml')]:
                if os.path.exists(candidate): return candidate
        if clean == '/robots.txt':
            for candidate in [os.path.join(SERVER_DIR, 'robots.txt'), os.path.join(os.path.dirname(SERVER_DIR), 'robots.txt')]:
                if os.path.exists(candidate): return candidate
        if clean in ['/ytdownloader', '/streamvault', '/home', '/experience', '/youtube', '/contact', '/feedback', '/stats', ''] or not os.path.exists(os.path.join(SERVER_DIR, clean.lstrip('/'))):
            clean = '/index.html'
        return os.path.join(SERVER_DIR, clean.lstrip('/'))

    def do_POST(self):
        parsed_path = urllib.parse.urlparse(self.path)
        clean_path = parsed_path.path.rstrip('/') or '/'
        if clean_path == '/api/info':
            content_len = int(self.headers.get('Content-Length', 0))
            post_body = self.rfile.read(content_len)
            try:
                req_data = json.loads(post_body.decode('utf-8'))
                url = req_data.get('url', '').strip()
                if not url:
                    self._send_json({'error': 'Please provide a valid YouTube URL'}, 400)
                    return

                # 1. Fast Flat Metadata Pass (Guarantees 100% Real Title, Views, Duration, Channel)
                flat_info = {}
                try:
                    with yt_dlp.YoutubeDL({'quiet': True, 'no_warnings': True, 'extract_flat': True}) as ydl_flat:
                        f_res = ydl_flat.extract_info(url, download=False)
                        if f_res:
                            if 'entries' in f_res and f_res['entries']:
                                f_res = f_res['entries'][0]
                            flat_info = f_res
                except Exception:
                    pass

                client_options = [
                    ['android_vr', 'android'],
                    ['android'],
                    ['web']
                ]
                
                info = None
                last_err = None

                for client_list in client_options:
                    try:
                        cookies_path = os.path.join(os.path.dirname(__file__), 'cookies.txt')
                        ensure_youtube_cookies(cookies_path)
                        ydl_opts = {
                            'quiet': True,
                            'no_warnings': True,
                            'extract_flat': False,
                            'nocheckcertificate': True,
                            'geo_bypass': True,
                            'socket_timeout': 5,
                            'format_sort': ['res', 'fps', 'hdr:12', 'vcodec:vp9', 'vcodec:h264', 'acodec:m4a', 'acodec:opus'],
                            'extractor_args': {
                                'youtube': {
                                    'player_client': client_list,
                                    'player_skip': ['configs', 'webpage'],
                                }
                            },
                        }
                        if DENO_EXE_PATH:
                            ydl_opts['js_runtimes'] = {'deno': {'path': DENO_EXE_PATH}}# Do not pass invalid cookiefile - clean requests bypass bot checks on cloud IPs
                        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                            info = ydl.extract_info(url, download=False)
                            if info:
                                break
                    except Exception as ex:
                        last_err = ex
                        continue

                if not info:
                    print(f"yt-dlp info exception, using flat_info / fallback engine: {last_err}")

                if info:
                    if 'entries' in info: info = info['entries'][0]
                    video_id = info.get('id', '') or flat_info.get('id', '')
                    title = info.get('title') or flat_info.get('title', 'Unknown Title')
                    thumbnail = f"https://img.youtube.com/vi/{video_id}/hqdefault.jpg" if video_id else "https://img.youtube.com/vi/U0EI7XFkkV4/hqdefault.jpg"
                    duration_sec = info.get('duration') or flat_info.get('duration', 0)
                    channel = info.get('uploader') or info.get('channel') or flat_info.get('uploader') or flat_info.get('channel', 'Unknown Channel')
                    view_count = info.get('view_count') or flat_info.get('view_count', 0)
                    if not view_count or view_count == 0:
                        view_count = get_real_youtube_metadata(video_id)

                    formats_raw = info.get('formats', [])
                    video_options = []
                    audio_options = []
                    seen_res = set()
                    seen_audio = set()

                    for f in formats_raw:
                        vcodec = f.get('vcodec', 'none')
                        acodec = f.get('acodec', 'none')
                        height = f.get('height')
                        ext = f.get('ext', 'mp4')
                        filesize = f.get('filesize') or f.get('filesize_approx')
                        fps = f.get('fps')

                        if vcodec != 'none' and height and height >= 144:
                            res_key = f"{height}p"
                            if fps and int(fps) > 30: res_key += f"{int(fps)}"
                            if res_key not in seen_res:
                                seen_res.add(res_key)
                                res_label = f"{height}p 4K Ultra HD (Original)" if height >= 2160 else f"{height}p 2K QHD (Original)" if height >= 1440 else f"{height}p HD (Original)" if height >= 720 else f"{height}p (Original)"
                                if fps and int(fps) > 30: res_label += f" {int(fps)}fps"
                                video_options.append({
                                    'format_id': f.get('format_id'),
                                    'quality': f"{height}p",
                                    'resolution': res_label,
                                    'ext': 'mp4' if ext in ['mp4', 'webm'] else ext,
                                    'filesize_str': format_size(filesize),
                                    'fps': fps or 30,
                                    'has_audio': acodec != 'none'
                                })

                    if len(video_options) < 3:
                        std_qualities = [
                            ('2160p', '2160p 4K Ultra HD (Original)', 'bestvideo[height<=2160]+bestaudio/best[height<=2160]/best', 'Original 4K'),
                            ('1440p', '1440p 2K QHD (Original)', 'bestvideo[height<=1440]+bestaudio/best[height<=1440]/best', 'Original 2K'),
                            ('1080p', '1080p Full HD (Original)', 'bestvideo[height<=1080]+bestaudio/best[height<=1080]/best', 'Original HD'),
                            ('720p', '720p HD (Original)', 'bestvideo[height<=720]+bestaudio/best[height<=720]/best', 'HD Stream'),
                            ('480p', '480p SD (Original)', 'bestvideo[height<=480]+bestaudio/best[height<=480]/best', 'Standard Stream'),
                            ('360p', '360p Mobile (Original)', 'bestvideo[height<=360]+bestaudio/best[height<=360]/best', 'Fast Download')
                        ]
                        for q_code, q_res, q_fmt, q_sz in std_qualities:
                            if q_code not in seen_res:
                                seen_res.add(q_code)
                                video_options.append({
                                    'format_id': q_fmt,
                                    'quality': q_code,
                                    'resolution': q_res,
                                    'ext': 'mp4',
                                    'filesize_str': q_sz,
                                    'fps': 30,
                                    'has_audio': True
                                })

                    video_options.sort(key=lambda x: int(x['quality'].replace('p', '')), reverse=True)

                    for f in formats_raw:
                        vcodec = f.get('vcodec', 'none')
                        acodec = f.get('acodec', 'none')
                        abr = f.get('abr')
                        ext = f.get('ext', 'm4a')
                        filesize = f.get('filesize') or f.get('filesize_approx')

                        if vcodec == 'none' and acodec != 'none':
                            bitrate = int(abr) if abr else 320
                            q_str = f"{bitrate} kbps Original"
                            if q_str not in seen_audio:
                                seen_audio.add(q_str)
                                audio_options.append({
                                    'format_id': f.get('format_id'),
                                    'quality': q_str,
                                    'ext': 'mp3',
                                    'filesize_str': format_size(filesize),
                                    'bitrate': bitrate
                                })

                    if not audio_options:
                        audio_options.append({
                            'format_id': 'bestaudio/best',
                            'quality': '320 kbps Original Lossless',
                            'ext': 'mp3',
                            'filesize_str': 'Original Stream',
                            'bitrate': 320
                        })

                    audio_options.sort(key=lambda x: x['bitrate'], reverse=True)

                    raw_views = 0
                    try:
                        raw_views = int(view_count) if view_count else 0
                    except:
                        pass
                    if raw_views == 0:
                        raw_views = get_real_youtube_metadata(video_id)
                    views_str = f"{raw_views:,} views" if raw_views > 0 else "Popular Video"

                    self._send_json({
                        'id': video_id, 'title': title, 'thumbnail': thumbnail,
                        'duration': format_duration(duration_sec), 'duration_sec': duration_sec,
                        'channel': channel, 'views': views_str, 'viewCount': raw_views,
                        'video_options': video_options, 'audio_options': audio_options
                    })
                else:
                    video_id_match = re.search(r'(?:v=|\/)([a-zA-Z0-9_-]{11})', url)
                    video_id = flat_info.get('id') or (video_id_match.group(1) if video_id_match else '')
                    
                    title = flat_info.get('title') or 'YouTube Video'
                    author = flat_info.get('uploader') or flat_info.get('channel') or 'YouTube Creator'
                    # Always use YouTube CDN thumbnail
                    thumbnail = f"https://img.youtube.com/vi/{video_id}/maxresdefault.jpg" if video_id else flat_info.get('thumbnail', '')
                    if not view_cnt or view_cnt == 0:
                        view_cnt = get_real_youtube_metadata(video_id)

                    raw_views = 0
                    try:
                        raw_views = int(view_cnt) if view_cnt else 0
                    except:
                        pass
                    views_str = f"{raw_views:,} views" if raw_views > 0 else "High Stream Volume"

                    if not title or title == 'YouTube Video' or dur_sec == 0:
                        try:
                            oembed_url = f'https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v={video_id}&format=json'
                            req = urllib.request.Request(oembed_url, headers={'User-Agent': 'Mozilla/5.0'})
                            with urllib.request.urlopen(req, timeout=5) as r:
                                o_data = json.loads(r.read().decode('utf-8'))
                                if not title or title == 'YouTube Video': title = o_data.get('title', title)
                                if not author or author == 'YouTube Creator': author = o_data.get('author_name', author)
                        except Exception:
                            pass

                    self._send_json({
                        'id': video_id,
                        'title': title,
                        'thumbnail': thumbnail,
                        'duration': format_duration(dur_sec) if dur_sec > 0 else '03:45',
                        'duration_sec': dur_sec or 225,
                        'channel': author,
                        'views': views_str,
                        'viewCount': raw_views,
                        'video_options': [
                            {'format_id': 'bestvideo[height<=2160]+bestaudio/best[height<=2160]/best', 'quality': '2160p', 'resolution': '2160p 4K Ultra HD (Original)', 'ext': 'mp4', 'filesize_str': 'Original 4K', 'fps': 60, 'has_audio': True},
                            {'format_id': 'bestvideo[height<=1440]+bestaudio/best[height<=1440]/best', 'quality': '1440p', 'resolution': '1440p 2K QHD (Original)', 'ext': 'mp4', 'filesize_str': 'Original 2K', 'fps': 60, 'has_audio': True},
                            {'format_id': 'bestvideo[height<=1080]+bestaudio/best[height<=1080]/best', 'quality': '1080p', 'resolution': '1080p Full HD (Original)', 'ext': 'mp4', 'filesize_str': 'Original HD', 'fps': 60, 'has_audio': True},
                            {'format_id': 'bestvideo[height<=720]+bestaudio/best[height<=720]/best', 'quality': '720p', 'resolution': '720p HD (Original)', 'ext': 'mp4', 'filesize_str': 'HD Stream', 'fps': 30, 'has_audio': True},
                            {'format_id': 'bestvideo[height<=480]+bestaudio/best[height<=480]/best', 'quality': '480p', 'resolution': '480p SD (Original)', 'ext': 'mp4', 'filesize_str': 'Standard Stream', 'fps': 30, 'has_audio': True},
                            {'format_id': 'bestvideo[height<=360]+bestaudio/best[height<=360]/best', 'quality': '360p', 'resolution': '360p Mobile', 'ext': 'mp4', 'filesize_str': 'Fast Download', 'fps': 30, 'has_audio': True}
                        ],
                        'audio_options': [
                            {'format_id': 'bestaudio/best', 'quality': '320 kbps Original', 'ext': 'mp3', 'filesize_str': 'High Quality Audio', 'bitrate': 320}
                        ]
                    })
            except Exception as e:
                self._send_json({'error': f'Failed to process YouTube URL: {str(e)}'}, 500)
        else:
            self._send_json({'error': 'Endpoint not found'}, 404)

    def do_GET(self):
        try:
            parsed_path = urllib.parse.urlparse(self.path)
            path_str = parsed_path.path
            query_params = urllib.parse.parse_qs(parsed_path.query)

            # Direct XML Sitemap serving
            if path_str in ['/sitemap.xml', '/sitemap']:
                for s_path in [os.path.join(SERVER_DIR, 'sitemap.xml'), os.path.join(os.path.dirname(SERVER_DIR), 'sitemap.xml')]:
                    if os.path.exists(s_path):
                        with open(s_path, 'rb') as f: content = f.read()
                        self.send_response(200)
                        self.send_header('Content-Type', 'application/xml; charset=utf-8')
                        self.send_header('Content-Length', str(len(content)))
                        self.end_headers()
                        self.wfile.write(content)
                        return

            # Direct robots.txt serving
            if path_str == '/robots.txt':
                for r_path in [os.path.join(SERVER_DIR, 'robots.txt'), os.path.join(os.path.dirname(SERVER_DIR), 'robots.txt')]:
                    if os.path.exists(r_path):
                        with open(r_path, 'rb') as f: content = f.read()
                        self.send_response(200)
                        self.send_header('Content-Type', 'text/plain; charset=utf-8')
                        self.send_header('Content-Length', str(len(content)))
                        self.end_headers()
                        self.wfile.write(content)
                        return

            # Real-time Download Progress Endpoint
            if path_str == '/api/progress':
                dl_id = query_params.get('download_id', [None])[0]
                prog_data = active_downloads.get(dl_id, {
                    'status': 'starting',
                    'percent': 5.0,
                    'downloaded_str': '0 MB',
                    'total_str': 'Connecting...',
                    'speed_str': '...',
                    'eta_str': '...'
                })
                self._send_json(prog_data)
                return

            # StreamVault Download API Endpoint
            if path_str == '/api/download':
                url = query_params.get('url', [None])[0]
                format_id = query_params.get('format_id', ['best'])[0]
                media_type = query_params.get('type', ['video'])[0]
                title_param = query_params.get('title', ['downloaded_media'])[0]
                start_time_param = query_params.get('start_time', [None])[0]
                end_time_param = query_params.get('end_time', [None])[0]
                quality_param = query_params.get('quality', [''])[0]
                download_id = query_params.get('download_id', [None])[0] or str(uuid.uuid4())

                if not url:
                    self._send_json({'error': 'Missing YouTube URL'}, 400)
                    return

                safe_title = re.sub(r'[^\w\s-]', '', title_param).strip().replace(' ', '_') or 'youtube_media'
                start_sec = parse_time_to_seconds(start_time_param)
                end_sec = parse_time_to_seconds(end_time_param)
                is_trimmed = start_sec is not None or end_sec is not None
                if is_trimmed: safe_title += '_trimmed'

                temp_dir = tempfile.mkdtemp()
                out_template = os.path.join(temp_dir, f"{safe_title}.%(ext)s")

                def yt_progress_hook(d):
                    if d['status'] == 'downloading':
                        total = d.get('total_bytes') or d.get('total_bytes_estimate') or 0
                        downloaded = d.get('downloaded_bytes', 0)
                        speed = d.get('speed') or 0
                        eta = d.get('eta') or 0
                        pct = (downloaded / total * 100) if total > 0 else 0.0

                        active_downloads[download_id] = {
                            'status': 'downloading',
                            'downloaded_bytes': downloaded,
                            'total_bytes': total,
                            'percent': round(pct, 1),
                            'downloaded_str': format_size(downloaded),
                            'total_str': format_size(total),
                            'speed_str': f"{format_size(speed)}/s" if speed else "Calculating...",
                            'eta_str': f"{eta}s" if eta else "..."
                        }
                    elif d['status'] == 'finished':
                        active_downloads[download_id] = {
                            'status': 'processing',
                            'percent': 98.0,
                            'downloaded_str': 'Downloaded',
                            'total_str': 'Merging Streams...',
                            'speed_str': 'FFmpeg Processing',
                            'eta_str': '0s'
                        }

                client_options = [
                    ['android'],
                    ['android_vr']
                ]

                direct_stream_downloaded = False
                target_out = os.path.join(temp_dir, f"media.{'mp3' if media_type == 'audio' else 'mp4'}")

                try:
                    from pytubefix import YouTube
                    yt_obj = YouTube(url, client='MWEB')
                    stream = None
                    if media_type == 'audio':
                        stream = yt_obj.streams.filter(only_audio=True).first() or yt_obj.streams.filter(progressive=True).first()
                    else:
                        height_match = re.search(r'(\d+)p', quality_param)
                        target_h = height_match.group(1) if height_match else ''
                        if target_h:
                            stream = yt_obj.streams.filter(res=f"{target_h}p", progressive=True).first()
                        if not stream:
                            stream = yt_obj.streams.get_highest_resolution() or yt_obj.streams.filter(progressive=True).first()

                    if stream and stream.url:
                        target_pytube = os.path.join(temp_dir, f"{safe_title}.mp4")
                        req_p = urllib.request.Request(stream.url, headers={'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X)'})
                        with urllib.request.urlopen(req_p, timeout=60) as resp_p, open(target_pytube, 'wb') as out_p:
                            shutil.copyfileobj(resp_p, out_p)
                        if os.path.exists(target_pytube) and os.path.getsize(target_pytube) > 0:
                            download_success = True
                            direct_stream_downloaded = True
                except Exception as e_pt:
                    print(f"PyTubeFix primary extraction error: {e_pt}")

                if not direct_stream_downloaded:
                    for client_list in client_options:
                    try:
                        ydl_opts_meta = {
                            'quiet': True,
                            'no_warnings': True,
                            'extract_flat': False,
                            'nocheckcertificate': True,
                            'geo_bypass': True,
                            'socket_timeout': 15,
                            'format_sort': ['res', 'fps', 'hdr:12', 'vcodec:vp9', 'vcodec:h264', 'acodec:m4a', 'acodec:opus'],
                            'extractor_args': {
                                'youtube': {
                                    'player_client': client_list,
                                    'player_skip': ['configs', 'webpage'],
                                }
                            },
                        }
                        if DENO_EXE_PATH:
                            ydl_opts_meta['js_runtimes'] = {'deno': {'path': DENO_EXE_PATH}}
                        with yt_dlp.YoutubeDL(ydl_opts_meta) as ydl_m:
                            info_m = ydl_m.extract_info(url, download=False)
                            if info_m:
                                formats_m = info_m.get('formats', [])
                                stream_url = None
                                stream_hdrs = {'User-Agent': 'Mozilla/5.0'}

                                if media_type == 'audio':
                                    for f in formats_m:
                                        if f.get('acodec') != 'none' and f.get('vcodec') == 'none' and f.get('url'):
                                            stream_url = f.get('url')
                                            stream_hdrs = f.get('http_headers', stream_hdrs)
                                            break
                                    if not stream_url and formats_m:
                                        for f in formats_m:
                                            if f.get('url'):
                                                stream_url = f.get('url')
                                                stream_hdrs = f.get('http_headers', stream_hdrs)
                                                break
                                else:
                                    height_match = re.search(r'(\d+)p', quality_param)
                                    target_h = int(height_match.group(1)) if height_match else 0
                                    
                                    best_fmt = None
                                    for f in formats_m:
                                        if f.get('url') and f.get('vcodec') != 'none':
                                            h = f.get('height') or 0
                                            if target_h and h == target_h and f.get('acodec') != 'none':
                                                best_fmt = f
                                                break
                                            elif target_h and h == target_h:
                                                best_fmt = f
                                            elif not best_fmt or (h <= (target_h or 720) and h > 0):
                                                best_fmt = f
                                    
                                    if best_fmt:
                                        stream_url = best_fmt.get('url')
                                        stream_hdrs = best_fmt.get('http_headers', stream_hdrs)

                                if stream_url:
                                    req_s = urllib.request.Request(stream_url, headers=stream_hdrs)
                                    with urllib.request.urlopen(req_s, timeout=60) as resp_s, open(target_out, 'wb') as out_f:
                                        shutil.copyfileobj(resp_s, out_f)
                                    if os.path.exists(target_out) and os.path.getsize(target_out) > 0:
                                        download_success = True
                                        direct_stream_downloaded = True
                                        break
                    except Exception as e_stream:
                        print(f"Direct stream extraction error with {client_list}: {e_stream}")
                        continue

                if not direct_stream_downloaded:
                    for client_list in client_options:
                        try:
                            ydl_opts = {
                                'outtmpl': out_template,
                                'quiet': True,
                                'no_warnings': True,
                                'nocheckcertificate': True,
                                'geo_bypass': True,
                                'socket_timeout': 30,
                                'retries': 5,
                                'fragment_retries': 5,
                                'ffmpeg_location': imageio_ffmpeg.get_ffmpeg_exe(),
                                'format_sort': ['res', 'fps', 'hdr:12', 'vcodec:vp9', 'vcodec:h264'],
                                'concurrent_fragment_downloads': 4,
                                'buffersize': 1024 * 1024,
                                'merge_output_format': 'mp4',
                                'progress_hooks': [yt_progress_hook],
                                'extractor_args': {
                                    'youtube': {
                                        'player_client': client_list,
                                        'player_skip': ['configs', 'webpage'],
                                    }
                                },
                            }
                            if DENO_EXE_PATH:
                                ydl_opts['js_runtimes'] = {'deno': {'path': DENO_EXE_PATH}}

                            if is_trimmed:
                                ydl_opts['download_ranges'] = yt_dlp.utils.download_range_func(None, [(start_sec or 0, end_sec or float('inf'))])
                                ydl_opts['force_keyframes_at_cuts'] = True

                            if media_type == 'audio':
                                ydl_opts['format'] = 'bestaudio/best'
                                if query_params.get('raw', ['false'])[0] != 'true':
                                    ydl_opts['postprocessors'] = [{
                                        'key': 'FFmpegExtractAudio',
                                        'preferredcodec': 'mp3',
                                        'preferredquality': '320'
                                    }]
                            else:
                                height_match = re.search(r'(\d+)p', quality_param)
                                target_h = height_match.group(1) if height_match else ''
                                if target_h:
                                    ydl_opts['format'] = f"18/22/b/best[height<={target_h}]/best"
                                else:
                                    ydl_opts['format'] = "18/22/b/best"

                                if not is_trimmed:
                                    ydl_opts['postprocessor_args'] = {
                                        'ffmpeg': [
                                            '-c:v', 'copy',
                                            '-c:a', 'aac',
                                            '-b:a', '320k'
                                        ]
                                    }
                                else:
                                    ydl_opts['postprocessor_args'] = {
                                        'ffmpeg': [
                                            '-avoid_negative_ts', 'make_zero',
                                            '-c:v', 'libx264',
                                            '-preset', 'medium',
                                            '-crf', '14',
                                            '-c:a', 'aac',
                                            '-b:a', '320k',
                                            '-async', '1'
                                        ]
                                    }

                            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                                ydl.download([url])

                            media_files = [f for f in os.listdir(temp_dir) if not f.endswith('.txt') and not f.endswith('.part') and not f.endswith('.ytdl')]
                            if media_files:
                                download_success = True
                                break
                        except Exception as e_dl:
                            last_dl_err = e_dl
                if not download_success:
                    try:
                        from pytubefix import YouTube
                        yt_obj = YouTube(url, client='MWEB')
                        stream = None
                        if media_type == 'audio':
                            stream = yt_obj.streams.filter(only_audio=True).first() or yt_obj.streams.filter(progressive=True).first()
                        else:
                            height_match = re.search(r'(\d+)p', quality_param)
                            target_h = height_match.group(1) if height_match else ''
                            if target_h:
                                stream = yt_obj.streams.filter(res=f"{target_h}p", progressive=True).first()
                            if not stream:
                                stream = yt_obj.streams.get_highest_resolution() or yt_obj.streams.filter(progressive=True).first()

                        if stream and stream.url:
                            target_pytube = os.path.join(temp_dir, f"{safe_title}.mp4")
                            req_p = urllib.request.Request(stream.url, headers={'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X)'})
                            with urllib.request.urlopen(req_p, timeout=60) as resp_p, open(target_pytube, 'wb') as out_p:
                                shutil.copyfileobj(resp_p, out_p)
                            if os.path.exists(target_pytube) and os.path.getsize(target_pytube) > 0:
                                download_success = True
                    except Exception as e_pt:
                        print(f"PyTubeFix fallback error: {e_pt}")

                try:
                    media_files = [f for f in os.listdir(temp_dir) if not f.endswith('.txt') and not f.endswith('.part') and not f.endswith('.ytdl')] if os.path.exists(temp_dir) else []
                    if not download_success or not media_files:
                        self._send_json({'error': f'Download failed: {str(last_dl_err or "No media downloaded")}'}, 500)
                        return

                    filename = media_files[0]
                    target_file = os.path.join(temp_dir, filename)
                    ext_lower = filename.split('.')[-1].lower()
                    mimetype = {'mp4': 'video/mp4', 'webm': 'video/webm', 'mp3': 'audio/mpeg', 'm4a': 'audio/mp4'}.get(ext_lower, 'application/octet-stream')

                    with open(target_file, 'rb') as f:
                        file_data = f.read()

                    self.send_response(200)
                    self.send_header('Content-Type', mimetype)
                    self.send_header('Content-Length', str(len(file_data)))
                    self.send_header('Content-Disposition', f'attachment; filename="{filename}"')
                    self.send_header('Access-Control-Allow-Origin', '*')
                    self.end_headers()
                    self.wfile.write(file_data)
                    return

                except Exception as e:
                    self._send_json({'error': f'Download failed: {str(e)}'}, 500)
                    return
                finally:
                    stop_monitor = True
                    try:
                        shutil.rmtree(temp_dir, ignore_errors=True)
                    except Exception:
                        pass

            # Endpoint 1: YouTube Studio Realtime API Endpoint
            if path_str == '/api/studio-realtime':
                self.send_response(200)
                self.send_header('Content-Type', 'application/json')
                self.send_header('Access-Control-Allow-Origin', '*')
                self.end_headers()

                subs, views, vids = self.get_studio_live_data()
                response_data = {
                    "success": True,
                    "subscriberCount": subs,
                    "viewCount": views,
                    "videoCount": vids,
                    "source": "YouTube Studio Direct Realtime Engine"
                }
                self.wfile.write(json.dumps(response_data).encode('utf-8'))
                return

            # Standard SPA Routing
            clean_path = path_str.rstrip('/').lower()
            if clean_path in ['/ytdownloader', '/streamvault', '/home', '/experience', '/youtube', '/contact', '/feedback', '/stats'] or (path_str != '/' and '.' not in path_str.split('/')[-1]):
                self.path = '/index.html'

            return super().do_GET()
        except Exception as err:
            print(f"Error in do_GET for path {self.path}: {err}")
            try:
                self._send_json({'error': str(err)}, 500)
            except Exception:
                pass

    def do_OPTIONS(self):
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-Requested-With')
        self.end_headers()

    def _send_json(self, data, status=200):
        self.send_response(status)
        self.send_header('Content-Type', 'application/json')
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type, Authorization, X-Requested-With')
        self.end_headers()
        self.wfile.write(json.dumps(data).encode('utf-8'))

    def end_headers(self):
        self.send_header('Cache-Control', 'no-cache, no-store, must-revalidate')
        self.send_header('Pragma', 'no-cache')
        self.send_header('Expires', '0')
        super().end_headers()

    def get_studio_live_data(self):
        return 1315, 16458, 30

class ThreadedHTTPServer(socketserver.ThreadingMixIn, http.server.HTTPServer):
    daemon_threads = True
    allow_reuse_address = True

if __name__ == '__main__':
    import socket
    try:
        local_ip = socket.gethostbyname(socket.gethostname())
    except Exception:
        local_ip = '127.0.0.1'
    print("=" * 60)
    print("  Amit Kushwaha Website & StreamVault Multi-Threaded Server is running!")
    print(f"  Desktop URL:  http://127.0.0.1:{PORT}")
    print(f"  Mobile URL:   http://{local_ip}:{PORT}  (same WiFi)")
    print(f"  YT Downloader: http://{local_ip}:{PORT}/ytdownloader")
    print("=" * 60)
    httpd = ThreadedHTTPServer(("", PORT), SPAServer)
    httpd.serve_forever()
